-- Migration 230: Basketplan person staging + nation lookup.
--
-- Basketplan (Swiss Basketball, club 166) is the ISSUING authority for basketball
-- licences and — unlike every register we already mirror — carries nationality on
-- 100% of licensed people. It is reached only through an authenticated browser
-- session (the login hashes the password client-side, so no curl), so this is a
-- Playwright scrape into a staging table, mirroring the ClubDesk pattern:
-- scrape -> staging -> FILL-ONLY passes, never a direct write to members.
--
-- ── basketplan_nations ───────────────────────────────────────────────────────
-- Basketplan's nationality picklist is 297 options whose VALUE is an internal
-- numeric id and whose LABEL is a FRENCH country name — hardcoded, identical
-- under locale=de/it/fr. So neither our German/English COUNTRY_NAME_TO_CODE nor
-- Intl at runtime can resolve it; the numeric id is the only stable key, and it
-- is mapped once, here.
--
-- ⚠ 116 of the 296 options are NOT mapped, on purpose. 93 are legacy
-- abbreviation entries (`D`, `ALL`, `A`, `BRD`, `YUG`, `MAC`, `CH1`,
-- `Suisse pour FSBA`…) that coexist as SEPARATE options beside the proper names
-- and are still in live use; some are genuinely ambiguous (`MAC` = Macedonia or
-- Macao?). The rest are territories outside our 196-country list (Aruba, Guam,
-- Palau, Puerto Rico, the Virgin Islands…). All are stored with iso = NULL and
-- ambiguous = true so the fill pass SKIPS them and reports them for a human,
-- rather than guessing a nationality onto a real person. Observed impact is
-- small: in an 86-person sample only two assertions were unmapped (`MAC` x1,
-- `D` x1) out of 90 — `D` is almost certainly Germany but is deliberately left
-- for a human to confirm.
--
-- ── basketplan_people ────────────────────────────────────────────────────────
-- One row per scraped person, keyed by Basketplan's personId. Deliberately holds
-- ONLY what we intend to consume — nationality, the officials qualifications and
-- their acquisition dates, the trained-in-Switzerland flag and licence number.
-- Addresses, birthdates, AHV and IBAN are NOT staged: Basketplan's addresses are
-- frequently worse than ours (`Hagenbuchrain` vs our correct `Hagenbuchrain 38`),
-- it holds at least one corrupt birthdate ("0996"), and the AHV/IBAN fields are
-- sparse, high-sensitivity and visible for minors. Not staging them is the
-- simplest guarantee they can never leak into members.
--
-- Schema-only + idempotent.

BEGIN;

CREATE TABLE IF NOT EXISTS basketplan_nations (
  bp_id     integer PRIMARY KEY,
  iso       varchar(2),
  label_fr  text NOT NULL,
  ambiguous boolean NOT NULL DEFAULT false
);

COMMENT ON TABLE basketplan_nations IS
  'Basketplan nationality picklist: internal numeric id -> ISO 3166-1 alpha-2. Labels are FRENCH and hardcoded regardless of UI locale. ambiguous = legacy abbreviation or an unsupported territory; those must never be auto-applied.';

INSERT INTO basketplan_nations (bp_id, iso, label_fr, ambiguous) VALUES
  (1, NULL, 'Suisse pour FSBA', true),
  (2, 'CH', 'Suisse', false),
  (3, 'SK', 'Slovaquie', false),
  (4, 'TR', 'Turquie', false),
  (5, 'IT', 'Italie', false),
  (6, 'LK', 'Sri Lanka', false),
  (7, 'CM', 'Cameroun', false),
  (8, 'PT', 'Portugal', false),
  (9, 'AU', 'Australie', false),
  (10, NULL, 'YUG', true),
  (11, 'XK', 'Kosovo', false),
  (12, 'DE', 'Allemagne', false),
  (13, 'BA', 'Bosnie-Herzégovine', false),
  (14, 'CO', 'Colombie', false),
  (15, 'FR', 'France', false),
  (16, 'FJ', 'Fidji', false),
  (17, 'HN', 'Honduras', false),
  (18, 'ID', 'Indonésie', false),
  (19, 'GR', 'Grèce', false),
  (20, 'ES', 'Espagne', false),
  (21, NULL, 'SER', true),
  (22, NULL, 'ERY', true),
  (23, 'SE', 'Suède', false),
  (24, 'TN', 'Tunisie', false),
  (25, 'CD', 'République démocratique du Congo', false),
  (26, 'US', 'Etats-Unis d''Amérique', false),
  (27, 'BO', 'Bolivie', false),
  (28, 'MU', 'Maurice', false),
  (29, 'NL', 'Pays-Bas', false),
  (30, 'SI', 'Slovénie', false),
  (31, 'BE', 'Belgique', false),
  (32, 'DO', 'République dominicaine', false),
  (33, 'HU', 'Hongrie', false),
  (34, 'EG', 'Egypte', false),
  (35, NULL, 'MAC', true),
  (36, 'IS', 'Islande', false),
  (37, 'CA', 'Canada', false),
  (38, 'HR', 'Croatie', false),
  (39, NULL, 'Côte d''Ivoire', true),
  (40, 'IQ', 'Iraq', false),
  (41, 'MX', 'Mexique', false),
  (42, 'SN', 'Sénégal', false),
  (43, 'AO', 'Angola', false),
  (44, 'DK', 'Danemark', false),
  (45, 'AT', 'Autriche', false),
  (46, 'DZ', 'Algérie', false),
  (47, 'RU', 'Fédération de Russie', false),
  (48, 'MN', 'Mongolie', false),
  (49, 'SO', 'Somalie', false),
  (50, 'MA', 'Maroc', false),
  (51, 'LV', 'Lettonie', false),
  (52, 'RO', 'Roumanie', false),
  (53, 'HT', 'Haïti', false),
  (54, 'GA', 'Gabon', false),
  (55, 'GN', 'Guinée', false),
  (56, 'NZ', 'Nouvelle-Zélande', false),
  (57, 'BI', 'Burundi', false),
  (58, NULL, 'République tchèque', true),
  (59, 'SC', 'Seychelles', false),
  (60, 'LB', 'Liban', false),
  (61, 'NI', 'Nicaragua', false),
  (62, 'BR', 'Brésil', false),
  (63, 'AL', 'Albanie', false),
  (64, NULL, 'IRN', true),
  (65, 'CL', 'Chili', false),
  (66, 'EC', 'Equateur', false),
  (67, 'IN', 'Inde', false),
  (68, 'UA', 'Ukraine', false),
  (69, 'PL', 'Pologne', false),
  (70, 'LR', 'Libéria', false),
  (71, 'IL', 'Israël', false),
  (72, NULL, 'TIB', true),
  (73, 'PE', 'Pérou', false),
  (74, 'GB', 'Grande-Bretagne', false),
  (75, 'KN', 'Saint-Kitts-et-Nevis', false),
  (76, 'IE', 'Irlande', false),
  (77, 'UY', 'Uruguay', false),
  (78, 'NO', 'Norvège', false),
  (79, 'PK', 'Pakistan', false),
  (80, 'CG', 'Congo', false),
  (81, 'KE', 'Kenya', false),
  (82, 'KH', 'Cambodge', false),
  (83, 'CU', 'Cuba', false),
  (84, 'BG', 'Bulgarie', false),
  (85, 'CV', 'Cap-Vert', false),
  (86, 'AG', 'Antigua-et-Barbuda', false),
  (87, 'AF', 'Afghanistan', false),
  (88, 'AR', 'Argentine', false),
  (89, 'TH', 'Thaïlande', false),
  (90, 'PH', 'Philippines', false),
  (91, 'ET', 'Ethiopie', false),
  (92, NULL, 'République populaire', true),
  (93, 'MG', 'Madagascar', false),
  (94, 'ZA', 'Afrique du Sud', false),
  (95, 'GH', 'Ghana', false),
  (96, NULL, 'Vietnam', true),
  (97, 'LI', 'Liechtenstein', false),
  (98, 'LT', 'Lituanie', false),
  (99, 'FI', 'Finlande', false),
  (100, NULL, 'République populaire démocratique de Corée', true),
  (101, 'RW', 'Rwanda', false),
  (102, 'NG', 'Nigéria', false),
  (103, 'KR', 'Corée', false),
  (104, 'ZM', 'Zambie', false),
  (105, 'ZW', 'Zimbabwe', false),
  (106, NULL, 'ZAI', true),
  (107, 'PA', 'Panama', false),
  (108, 'GT', 'Guatemala', false),
  (109, 'BJ', 'Bénin', false),
  (110, 'YE', 'Yémen', false),
  (111, 'JP', 'Japon', false),
  (112, 'TW', 'Chinese Taipei', false),
  (113, NULL, 'Swaziland', true),
  (114, NULL, 'KUR', true),
  (115, 'CR', 'Costa Rica', false),
  (116, 'TG', 'Togo', false),
  (117, 'BH', 'Bahreïn', false),
  (118, 'BY', 'Bélarus', false),
  (119, 'DM', 'Dominique', false),
  (120, 'LU', 'Luxembourg', false),
  (121, NULL, 'APA', true),
  (122, 'TD', 'Tchad', false),
  (123, 'GY', 'Guyana', false),
  (124, 'ML', 'Mali', false),
  (125, 'SV', 'El Salvador', false),
  (126, NULL, 'République démocratique Populaire Lao', true),
  (127, 'NE', 'Niger', false),
  (128, NULL, 'République islamique d''Iran', true),
  (129, 'BF', 'Burkina Faso', false),
  (130, 'SY', 'République arabe syrienne', false),
  (131, 'PS', 'Palestine', false),
  (132, 'BD', 'Bangladesh', false),
  (133, NULL, 'République-Unie de Tanzanie', true),
  (134, 'KZ', 'Kazakhstan', false),
  (135, 'BS', 'Bahamas', false),
  (136, 'JM', 'Jamaïque', false),
  (137, 'MR', 'Mauritanie', false),
  (138, 'MD', 'République de Moldova', false),
  (139, 'AZ', 'Azerbaïdjan', false),
  (140, 'UZ', 'Ouzbékistan', false),
  (141, NULL, 'Ex-République yougoslave de Macédonie', true),
  (142, 'MY', 'Malaisie', false),
  (143, 'GE', 'Géorgie', false),
  (144, 'SD', 'Soudan', false),
  (145, 'NA', 'Namibie', false),
  (146, NULL, 'CH1', true),
  (147, NULL, 'BOS', true),
  (148, NULL, 'BRD', true),
  (149, NULL, 'JAP', true),
  (150, NULL, 'IRK', true),
  (151, NULL, 'KRO', true),
  (152, NULL, 'IRA', true),
  (153, NULL, 'CEY', true),
  (154, NULL, 'HR', true),
  (155, NULL, 'H', true),
  (156, NULL, 'BRE', true),
  (157, 'GM', 'Gambie', false),
  (158, NULL, 'IVO', true),
  (159, NULL, 'GB', true),
  (160, NULL, 'YU', true),
  (161, 'PY', 'Paraguay', false),
  (162, NULL, 'BH', true),
  (163, NULL, 'TCH', true),
  (164, NULL, 'I', true),
  (165, NULL, 'FL', true),
  (166, NULL, 'NL', true),
  (167, NULL, 'D', true),
  (168, 'SL', 'Sierra Leone', false),
  (169, NULL, 'GR', true),
  (170, NULL, 'K', true),
  (171, NULL, 'CON', true),
  (172, NULL, 'F', true),
  (173, NULL, 'C', true),
  (174, NULL, 'ENG', true),
  (175, NULL, 'ALL', true),
  (176, NULL, 'ROU', true),
  (177, NULL, 'COR', true),
  (178, 'VE', 'Venezuela', false),
  (179, NULL, 'LET', true),
  (180, NULL, 'CZ', true),
  (181, NULL, 'SPA', true),
  (182, NULL, 'E', true),
  (183, NULL, 'KAM', true),
  (184, NULL, 'BR', true),
  (185, NULL, 'UK', true),
  (186, NULL, 'AL', true),
  (187, NULL, 'TR', true),
  (188, NULL, 'ARA', true),
  (189, NULL, 'TAM', true),
  (190, NULL, 'DEU', true),
  (191, NULL, 'YOU', true),
  (192, NULL, 'MK', true),
  (193, NULL, 'ET', true),
  (194, NULL, 'BO', true),
  (195, NULL, 'CHY', true),
  (196, NULL, 'GE', true),
  (197, NULL, 'HOL', true),
  (198, 'MC', 'Monaco', false),
  (199, NULL, 'MAZ', true),
  (200, NULL, 'SOU', true),
  (201, NULL, 'OUG', true),
  (202, NULL, 'A', true),
  (203, NULL, 'GRB', true),
  (204, NULL, 'BHR', true),
  (205, NULL, 'KIR', true),
  (206, 'UG', 'Ouganda', false),
  (207, NULL, 'UMU', true),
  (208, NULL, 'RD', true),
  (209, NULL, 'CHL', true),
  (210, NULL, 'PL', true),
  (211, NULL, 'JUG', true),
  (212, NULL, 'CU', true),
  (213, NULL, 'SUE', true),
  (214, NULL, 'TUK', true),
  (215, 'NP', 'Népal', false),
  (216, NULL, 'MAK', true),
  (217, NULL, 'TK', true),
  (218, NULL, 'JO', true),
  (219, NULL, 'MAL', true),
  (220, NULL, 'PE', true),
  (221, NULL, 'DK', true),
  (222, NULL, 'FIL', true),
  (223, NULL, 'HER', true),
  (224, 'EE', 'Estonie', false),
  (225, NULL, 'MAU', true),
  (226, NULL, 'P', true),
  (227, NULL, 'DAN', true),
  (228, NULL, 'CSR', true),
  (229, NULL, 'RUA', true),
  (230, NULL, 'NE', true),
  (231, NULL, 'SAL', true),
  (232, NULL, 'MOS', true),
  (233, 'MZ', 'Mozambique', false),
  (234, NULL, 'ZAR', true),
  (235, NULL, 'FR', true),
  (236, NULL, 'CVI', true),
  (237, NULL, 'SRL', true),
  (238, NULL, 'Samoa américaines', true),
  (239, 'AD', 'Andorre', false),
  (240, 'AM', 'Arménie', false),
  (241, NULL, 'Aruba', true),
  (242, 'BB', 'Barbade', false),
  (243, 'BZ', 'Belize', false),
  (244, NULL, 'Bermudes', true),
  (245, 'BT', 'Bhoutan', false),
  (246, 'BW', 'Botswana', false),
  (247, NULL, 'Iles Vierges britanniques', true),
  (248, 'BN', 'Brunéi Darussalam', false),
  (249, NULL, 'Iles Caïmans', true),
  (250, 'CF', 'République centrafricaine', false),
  (251, 'KM', 'Comores', false),
  (252, NULL, 'Iles Cook', true),
  (253, 'CY', 'Chypre', false),
  (254, 'DJ', 'Djibouti', false),
  (255, 'GQ', 'Guinée équatoriale', false),
  (256, 'ER', 'Erythrée', false),
  (257, 'FM', 'Etats fédérés de Micronésie', false),
  (258, 'GD', 'Grenade', false),
  (259, NULL, 'Guam', true),
  (260, 'GW', 'Guinée-Bissau', false),
  (261, NULL, 'Hong-Kong, Chine', true),
  (262, 'JO', 'Jordanie', false),
  (263, 'KG', 'Kirghizistan', false),
  (264, 'KW', 'Koweït', false),
  (265, 'LS', 'Lesotho', false),
  (266, 'LY', 'Libye', false),
  (267, 'MW', 'Malawi', false),
  (268, 'MV', 'Maldives', false),
  (269, 'MT', 'Malte', false),
  (270, 'MM', 'Myanmar', false),
  (271, 'NR', 'Nauru', false),
  (272, NULL, 'Antilles néerlandaises', true),
  (273, 'OM', 'Oman', false),
  (274, NULL, 'Palau', true),
  (275, 'PG', 'Papouasie-Nouvelle Guinée', false),
  (276, NULL, 'Porto Rico', true),
  (277, 'QA', 'Qatar', false),
  (278, 'LC', 'Sainte-Lucie', false),
  (279, 'VC', 'Saint-Vincent-et-les Grenadines', false),
  (280, 'WS', 'Samoa', false),
  (281, NULL, 'Serbie et Monténegro', true),
  (282, 'SM', 'Saint-Marin', false),
  (283, 'ST', 'Sao Tomé-et-Principe', false),
  (284, 'SA', 'Arabie saoudite', false),
  (285, 'SG', 'Singapour', false),
  (286, 'SB', 'Iles Salomon', false),
  (287, 'SR', 'Suriname', false),
  (288, 'TJ', 'Tadjikistan', false),
  (289, 'TO', 'Tonga', false),
  (290, 'TT', 'Trinité-et-Tobago', false),
  (291, 'TM', 'Turkménistan', false),
  (292, 'AE', 'Emirats arabes unis', false),
  (293, 'VU', 'Vanuatu', false),
  (294, NULL, 'Iles Vierges', true),
  (295, 'RS', 'Serbie', false),
  (296, 'ME', 'Montenegro', false)
ON CONFLICT (bp_id) DO UPDATE
  SET iso = EXCLUDED.iso, label_fr = EXCLUDED.label_fr, ambiguous = EXCLUDED.ambiguous;

CREATE TABLE IF NOT EXISTS basketplan_people (
  person_id      integer PRIMARY KEY,
  last_name      text,
  first_name     text,
  birthdate      date,
  licence_nr     text,
  nation1_id     integer,
  nation2_id     integer,
  nation_confirmed boolean,
  trained_in_ch  boolean,
  otr1_since     date,
  otr2_since     date,
  otn1_since     date,
  otn2_since     date,
  referee_reg_since  date,
  referee_nat_since  date,
  referee_mini_since date,
  referee_youth_since date,
  last_scored_at date,
  scraped_at     timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE basketplan_people IS
  'Staging for the authenticated Basketplan person scrape (findPersonById.do). Holds only the fields we intend to consume — no address / AHV / IBAN, and birthdate is a cross-check aid only, never an overwrite source.';

CREATE INDEX IF NOT EXISTS basketplan_people_licence_nr_idx ON basketplan_people (licence_nr);

COMMIT;
