-- 343 — participation_visibility needs a SINGLE-column primary key
--
-- Migration 341 created the junction with a composite primary key:
--
--     PRIMARY KEY (participation, viewer_user)
--
-- which is correct Postgres and unusable by Directus. Directus models exactly one
-- primary key column per collection; a composite PK reads to its schema inspector as
-- NO primary key, and at boot it logs
--
--     Collection "participation_visibility" doesn't have a primary key column
--     and will be ignored
--
-- and drops the collection from `schema.collections` entirely.
--
-- ⚠⚠ THE COLLECTION BEING "IGNORED" IS NOT THE CONTAINED FAILURE IT SOUNDS LIKE.
-- 341 also registered a relation — participation_visibility.participation →
-- participations.visible_to — and setup-permissions.mjs then wrote a policy filter on
-- that `visible_to` alias. Resolving `participations` therefore dereferences a
-- collection that is not in the schema, so EVERY read of participations 500s with
-- `Cannot read properties of undefined (reading 'primary')` (and
-- `…(reading 'fields')` from /kscw/activities/*/with-participations, which goes
-- through ItemsService). Prod lost every RSVP read between 13:38 and the fix on
-- 26.08.2026 — the app rendered zero confirmations everywhere, which reads to a user
-- exactly like the data having been deleted. It had not been: 10,650 rows were sitting
-- untouched the whole time.
--
-- ⚠ It is NOT a permission bug and restarting does not fix it. `admin_access = true`
-- bypasses policy filters and still 500s, because the fault is in schema resolution,
-- below the permission layer. A restart re-reads the schema and re-derives the same
-- unsupported PK shape — the boot WARN simply reappears.
--
-- The fix is the standard Directus junction shape: a surrogate single-column PK, with
-- the real key demoted to a UNIQUE constraint.
--
-- ⚠ The UNIQUE is load-bearing, not decoration. refresh_participation_visibility()
-- inserts with a TARGETLESS `ON CONFLICT DO NOTHING`, which silently accepts whatever
-- unique constraints exist — with none on the pair it would not error, it would
-- accumulate duplicate visibility rows on every reconcile. Dropping the composite PK
-- without replacing its uniqueness is the quiet version of this bug.
--
-- Nothing else in 341 references the primary key: the view, the verifier, the
-- reconcile and all ~10 triggers join on (participation, viewer_user) by name.

BEGIN;

-- 1. Surrogate key. Added BEFORE the composite PK is dropped so the table is never
--    without a uniqueness guarantee inside the transaction.
ALTER TABLE participation_visibility
  ADD COLUMN IF NOT EXISTS id integer GENERATED BY DEFAULT AS IDENTITY;

-- 2. Preserve the real key as a UNIQUE constraint (see the ON CONFLICT note above).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'public.participation_visibility'::regclass
       AND conname  = 'participation_visibility_pair_uniq'
  ) THEN
    ALTER TABLE participation_visibility
      ADD CONSTRAINT participation_visibility_pair_uniq UNIQUE (participation, viewer_user);
  END IF;
END $$;

-- 3. Swap the primary key onto `id`.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'public.participation_visibility'::regclass
       AND contype  = 'p'
       AND array_length(conkey, 1) > 1
  ) THEN
    ALTER TABLE participation_visibility DROP CONSTRAINT participation_visibility_pkey;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'public.participation_visibility'::regclass
       AND contype  = 'p'
  ) THEN
    ALTER TABLE participation_visibility
      ADD CONSTRAINT participation_visibility_pkey PRIMARY KEY (id);
  END IF;
END $$;

-- 4. Register the new column so the Data Model page is not missing the key it now
--    sorts by. Hidden + readonly: this table is trigger-maintained output, and a
--    hand-edited row here is a permission grant nobody asked for.
INSERT INTO directus_fields (collection, field, special, interface, readonly, hidden, sort, width, note)
SELECT 'participation_visibility', 'id', NULL, 'input', true, true, 0, 'half',
       'Surrogate key. Directus cannot model the real key (participation, viewer_user) — it is a UNIQUE constraint instead. See migration 343.'
WHERE NOT EXISTS (
  SELECT 1 FROM directus_fields
   WHERE collection = 'participation_visibility' AND field = 'id');

COMMIT;

-- ⚠⚠ RESTART THE CONTAINER AFTER THIS. The schema shape Directus refuses to serve is
-- read at boot; the DB is correct the moment this commits, but the running process
-- keeps its ignore-this-collection decision until it re-reads. `participations` stays
-- 500 until then.
