// AUTO-GENERATED from the kscw-website country list (de + en names -> ISO 3166-1 alpha-2).
// Used by localizeCountryName() to translate a stored free-text country name
// (ClubDesk German, or member-typed in any language) into the viewer's language
// via Intl.DisplayNames. Regenerate if the website list changes.
export const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  "afghanistan": "AF",
  "albania": "AL",
  "albanien": "AL",
  "algeria": "DZ",
  "algerien": "DZ",
  "andorra": "AD",
  "angola": "AO",
  "antigua and barbuda": "AG",
  "antigua und barbuda": "AG",
  "argentina": "AR",
  "argentinien": "AR",
  "armenia": "AM",
  "armenien": "AM",
  "aserbaidschan": "AZ",
  "australia": "AU",
  "australien": "AU",
  "austria": "AT",
  "azerbaijan": "AZ",
  "bahamas": "BS",
  "bahrain": "BH",
  "bangladesch": "BD",
  "bangladesh": "BD",
  "barbados": "BB",
  "belarus": "BY",
  "belgien": "BE",
  "belgium": "BE",
  "belize": "BZ",
  "benin": "BJ",
  "bhutan": "BT",
  "bolivia": "BO",
  "bolivien": "BO",
  "bosnia and herzegovina": "BA",
  "bosnien und herzegowina": "BA",
  "botswana": "BW",
  "brasilien": "BR",
  "brazil": "BR",
  "brunei": "BN",
  "bulgaria": "BG",
  "bulgarien": "BG",
  "burkina faso": "BF",
  "burundi": "BI",
  "cambodia": "KH",
  "cameroon": "CM",
  "canada": "CA",
  "cape verde": "CV",
  "central african republic": "CF",
  "chad": "TD",
  "chile": "CL",
  "china": "CN",
  "colombia": "CO",
  "comoros": "KM",
  "congo (drc)": "CD",
  "congo (republic)": "CG",
  "costa rica": "CR",
  "croatia": "HR",
  "cuba": "CU",
  "cyprus": "CY",
  "czech republic": "CZ",
  "denmark": "DK",
  "deutschland": "DE",
  "djibouti": "DJ",
  "dominica": "DM",
  "dominican republic": "DO",
  "dominikanische republik": "DO",
  "dschibuti": "DJ",
  "dänemark": "DK",
  "ecuador": "EC",
  "egypt": "EG",
  "el salvador": "SV",
  "equatorial guinea": "GQ",
  "eritrea": "ER",
  "estland": "EE",
  "estonia": "EE",
  "eswatini": "SZ",
  "ethiopia": "ET",
  "fidschi": "FJ",
  "fiji": "FJ",
  "finland": "FI",
  "finnland": "FI",
  "france": "FR",
  "frankreich": "FR",
  "gabon": "GA",
  "gabun": "GA",
  "gambia": "GM",
  "georgia": "GE",
  "georgien": "GE",
  "germany": "DE",
  "ghana": "GH",
  "greece": "GR",
  "grenada": "GD",
  "griechenland": "GR",
  "guatemala": "GT",
  "guinea": "GN",
  "guinea-bissau": "GW",
  "guyana": "GY",
  "haiti": "HT",
  "honduras": "HN",
  "hungary": "HU",
  "iceland": "IS",
  "india": "IN",
  "indien": "IN",
  "indonesia": "ID",
  "indonesien": "ID",
  "irak": "IQ",
  "iran": "IR",
  "iraq": "IQ",
  "ireland": "IE",
  "irland": "IE",
  "island": "IS",
  "israel": "IL",
  "italien": "IT",
  "italy": "IT",
  "jamaica": "JM",
  "jamaika": "JM",
  "japan": "JP",
  "jemen": "YE",
  "jordan": "JO",
  "jordanien": "JO",
  "kambodscha": "KH",
  "kamerun": "CM",
  "kanada": "CA",
  "kap verde": "CV",
  "kasachstan": "KZ",
  "katar": "QA",
  "kazakhstan": "KZ",
  "kenia": "KE",
  "kenya": "KE",
  "kirgisistan": "KG",
  "kiribati": "KI",
  "kolumbien": "CO",
  "komoren": "KM",
  "kongo (dem. rep.)": "CD",
  "kongo (rep.)": "CG",
  "kosovo": "XK",
  "kroatien": "HR",
  "kuba": "CU",
  "kuwait": "KW",
  "kyrgyzstan": "KG",
  "laos": "LA",
  "latvia": "LV",
  "lebanon": "LB",
  "lesotho": "LS",
  "lettland": "LV",
  "libanon": "LB",
  "liberia": "LR",
  "libya": "LY",
  "libyen": "LY",
  "liechtenstein": "LI",
  "litauen": "LT",
  "lithuania": "LT",
  "luxembourg": "LU",
  "luxemburg": "LU",
  "madagascar": "MG",
  "madagaskar": "MG",
  "malawi": "MW",
  "malaysia": "MY",
  "maldives": "MV",
  "malediven": "MV",
  "mali": "ML",
  "malta": "MT",
  "marokko": "MA",
  "marshall islands": "MH",
  "marshallinseln": "MH",
  "mauretanien": "MR",
  "mauritania": "MR",
  "mauritius": "MU",
  "mexico": "MX",
  "mexiko": "MX",
  "micronesia": "FM",
  "mikronesien": "FM",
  "moldau": "MD",
  "moldova": "MD",
  "monaco": "MC",
  "mongolei": "MN",
  "mongolia": "MN",
  "montenegro": "ME",
  "morocco": "MA",
  "mosambik": "MZ",
  "mozambique": "MZ",
  "myanmar": "MM",
  "namibia": "NA",
  "nauru": "NR",
  "nepal": "NP",
  "netherlands": "NL",
  "neuseeland": "NZ",
  "new zealand": "NZ",
  "nicaragua": "NI",
  "niederlande": "NL",
  "niger": "NE",
  "nigeria": "NG",
  "nordkorea": "KP",
  "nordmazedonien": "MK",
  "north korea": "KP",
  "north macedonia": "MK",
  "norway": "NO",
  "norwegen": "NO",
  "oman": "OM",
  "pakistan": "PK",
  "palau": "PW",
  "palestine": "PS",
  "palästina": "PS",
  "panama": "PA",
  "papua new guinea": "PG",
  "papua-neuguinea": "PG",
  "paraguay": "PY",
  "peru": "PE",
  "philippinen": "PH",
  "philippines": "PH",
  "poland": "PL",
  "polen": "PL",
  "portugal": "PT",
  "qatar": "QA",
  "romania": "RO",
  "ruanda": "RW",
  "rumänien": "RO",
  "russia": "RU",
  "russland": "RU",
  "rwanda": "RW",
  "saint kitts and nevis": "KN",
  "saint lucia": "LC",
  "saint vincent and the grenadines": "VC",
  "salomonen": "SB",
  "sambia": "ZM",
  "samoa": "WS",
  "san marino": "SM",
  "saudi arabia": "SA",
  "saudi-arabien": "SA",
  "schweden": "SE",
  "schweiz": "CH",
  "senegal": "SN",
  "serbia": "RS",
  "serbien": "RS",
  "seychellen": "SC",
  "seychelles": "SC",
  "sierra leone": "SL",
  "simbabwe": "ZW",
  "singapore": "SG",
  "singapur": "SG",
  "slovakia": "SK",
  "slovenia": "SI",
  "slowakei": "SK",
  "slowenien": "SI",
  "solomon islands": "SB",
  "somalia": "SO",
  "south africa": "ZA",
  "south korea": "KR",
  "south sudan": "SS",
  "spain": "ES",
  "spanien": "ES",
  "sri lanka": "LK",
  "st. kitts und nevis": "KN",
  "st. lucia": "LC",
  "st. vincent und die grenadinen": "VC",
  "sudan": "SD",
  "suriname": "SR",
  "sweden": "SE",
  "switzerland": "CH",
  "syria": "SY",
  "syrien": "SY",
  "são tomé and príncipe": "ST",
  "são tomé und príncipe": "ST",
  "südafrika": "ZA",
  "südkorea": "KR",
  "südsudan": "SS",
  "tadschikistan": "TJ",
  "taiwan": "TW",
  "tajikistan": "TJ",
  "tansania": "TZ",
  "tanzania": "TZ",
  "thailand": "TH",
  "timor-leste": "TL",
  "togo": "TG",
  "tonga": "TO",
  "trinidad and tobago": "TT",
  "trinidad und tobago": "TT",
  "tschad": "TD",
  "tschechien": "CZ",
  "tunesien": "TN",
  "tunisia": "TN",
  "turkey": "TR",
  "turkmenistan": "TM",
  "tuvalu": "TV",
  "türkei": "TR",
  "uganda": "UG",
  "ukraine": "UA",
  "ungarn": "HU",
  "united arab emirates": "AE",
  "united kingdom": "GB",
  "united states": "US",
  "uruguay": "UY",
  "usbekistan": "UZ",
  "uzbekistan": "UZ",
  "vanuatu": "VU",
  "vatican city": "VA",
  "vatikanstadt": "VA",
  "venezuela": "VE",
  "vereinigte arabische emirate": "AE",
  "vereinigte staaten": "US",
  "vereinigtes königreich": "GB",
  "vietnam": "VN",
  "yemen": "YE",
  "zambia": "ZM",
  "zentralafrikanische republik": "CF",
  "zimbabwe": "ZW",
  "zypern": "CY",
  "ägypten": "EG",
  "äquatorialguinea": "GQ",
  "äthiopien": "ET",
  "österreich": "AT",
}
