// AUTO-GENERATED from the kscw-website country list (public/js/registration-form.js).
// Regenerate if that list changes — it is the canonical source and is also what
// seeded ClubDesk's "Nationalität" picklist, so the German names must match it
// exactly (7 of them differ from Intl.DisplayNames' CLDR spelling).
//
// `de` is the ClubDesk-facing spelling. Display labels in the UI come from
// Intl.DisplayNames in the viewer's language (see countryOptions) — `de`/`en`
// here are the fallback + the ClubDesk wire format.
export interface Country {
  /** ISO 3166-1 alpha-2 */
  code: string
  de: string
  en: string
}

export const COUNTRIES: readonly Country[] = [
  { code: 'AD', de: "Andorra", en: "Andorra" },
  { code: 'AE', de: "Vereinigte Arabische Emirate", en: "United Arab Emirates" },
  { code: 'AF', de: "Afghanistan", en: "Afghanistan" },
  { code: 'AG', de: "Antigua und Barbuda", en: "Antigua and Barbuda" },
  { code: 'AL', de: "Albanien", en: "Albania" },
  { code: 'AM', de: "Armenien", en: "Armenia" },
  { code: 'AO', de: "Angola", en: "Angola" },
  { code: 'AR', de: "Argentinien", en: "Argentina" },
  { code: 'AT', de: "Österreich", en: "Austria" },
  { code: 'AU', de: "Australien", en: "Australia" },
  { code: 'AZ', de: "Aserbaidschan", en: "Azerbaijan" },
  { code: 'BA', de: "Bosnien und Herzegowina", en: "Bosnia and Herzegovina" },
  { code: 'BB', de: "Barbados", en: "Barbados" },
  { code: 'BD', de: "Bangladesch", en: "Bangladesh" },
  { code: 'BE', de: "Belgien", en: "Belgium" },
  { code: 'BF', de: "Burkina Faso", en: "Burkina Faso" },
  { code: 'BG', de: "Bulgarien", en: "Bulgaria" },
  { code: 'BH', de: "Bahrain", en: "Bahrain" },
  { code: 'BI', de: "Burundi", en: "Burundi" },
  { code: 'BJ', de: "Benin", en: "Benin" },
  { code: 'BN', de: "Brunei", en: "Brunei" },
  { code: 'BO', de: "Bolivien", en: "Bolivia" },
  { code: 'BR', de: "Brasilien", en: "Brazil" },
  { code: 'BS', de: "Bahamas", en: "Bahamas" },
  { code: 'BT', de: "Bhutan", en: "Bhutan" },
  { code: 'BW', de: "Botswana", en: "Botswana" },
  { code: 'BY', de: "Belarus", en: "Belarus" },
  { code: 'BZ', de: "Belize", en: "Belize" },
  { code: 'CA', de: "Kanada", en: "Canada" },
  { code: 'CD', de: "Kongo (Dem. Rep.)", en: "Congo (DRC)" },
  { code: 'CF', de: "Zentralafrikanische Republik", en: "Central African Republic" },
  { code: 'CG', de: "Kongo (Rep.)", en: "Congo (Republic)" },
  { code: 'CH', de: "Schweiz", en: "Switzerland" },
  { code: 'CL', de: "Chile", en: "Chile" },
  { code: 'CM', de: "Kamerun", en: "Cameroon" },
  { code: 'CN', de: "China", en: "China" },
  { code: 'CO', de: "Kolumbien", en: "Colombia" },
  { code: 'CR', de: "Costa Rica", en: "Costa Rica" },
  { code: 'CU', de: "Kuba", en: "Cuba" },
  { code: 'CV', de: "Kap Verde", en: "Cape Verde" },
  { code: 'CY', de: "Zypern", en: "Cyprus" },
  { code: 'CZ', de: "Tschechien", en: "Czech Republic" },
  { code: 'DE', de: "Deutschland", en: "Germany" },
  { code: 'DJ', de: "Dschibuti", en: "Djibouti" },
  { code: 'DK', de: "Dänemark", en: "Denmark" },
  { code: 'DM', de: "Dominica", en: "Dominica" },
  { code: 'DO', de: "Dominikanische Republik", en: "Dominican Republic" },
  { code: 'DZ', de: "Algerien", en: "Algeria" },
  { code: 'EC', de: "Ecuador", en: "Ecuador" },
  { code: 'EE', de: "Estland", en: "Estonia" },
  { code: 'EG', de: "Ägypten", en: "Egypt" },
  { code: 'ER', de: "Eritrea", en: "Eritrea" },
  { code: 'ES', de: "Spanien", en: "Spain" },
  { code: 'ET', de: "Äthiopien", en: "Ethiopia" },
  { code: 'FI', de: "Finnland", en: "Finland" },
  { code: 'FJ', de: "Fidschi", en: "Fiji" },
  { code: 'FM', de: "Mikronesien", en: "Micronesia" },
  { code: 'FR', de: "Frankreich", en: "France" },
  { code: 'GA', de: "Gabun", en: "Gabon" },
  { code: 'GB', de: "Vereinigtes Königreich", en: "United Kingdom" },
  { code: 'GD', de: "Grenada", en: "Grenada" },
  { code: 'GE', de: "Georgien", en: "Georgia" },
  { code: 'GH', de: "Ghana", en: "Ghana" },
  { code: 'GM', de: "Gambia", en: "Gambia" },
  { code: 'GN', de: "Guinea", en: "Guinea" },
  { code: 'GQ', de: "Äquatorialguinea", en: "Equatorial Guinea" },
  { code: 'GR', de: "Griechenland", en: "Greece" },
  { code: 'GT', de: "Guatemala", en: "Guatemala" },
  { code: 'GW', de: "Guinea-Bissau", en: "Guinea-Bissau" },
  { code: 'GY', de: "Guyana", en: "Guyana" },
  { code: 'HN', de: "Honduras", en: "Honduras" },
  { code: 'HR', de: "Kroatien", en: "Croatia" },
  { code: 'HT', de: "Haiti", en: "Haiti" },
  { code: 'HU', de: "Ungarn", en: "Hungary" },
  { code: 'ID', de: "Indonesien", en: "Indonesia" },
  { code: 'IE', de: "Irland", en: "Ireland" },
  { code: 'IL', de: "Israel", en: "Israel" },
  { code: 'IN', de: "Indien", en: "India" },
  { code: 'IQ', de: "Irak", en: "Iraq" },
  { code: 'IR', de: "Iran", en: "Iran" },
  { code: 'IS', de: "Island", en: "Iceland" },
  { code: 'IT', de: "Italien", en: "Italy" },
  { code: 'JM', de: "Jamaika", en: "Jamaica" },
  { code: 'JO', de: "Jordanien", en: "Jordan" },
  { code: 'JP', de: "Japan", en: "Japan" },
  { code: 'KE', de: "Kenia", en: "Kenya" },
  { code: 'KG', de: "Kirgisistan", en: "Kyrgyzstan" },
  { code: 'KH', de: "Kambodscha", en: "Cambodia" },
  { code: 'KI', de: "Kiribati", en: "Kiribati" },
  { code: 'KM', de: "Komoren", en: "Comoros" },
  { code: 'KN', de: "St. Kitts und Nevis", en: "Saint Kitts and Nevis" },
  { code: 'KP', de: "Nordkorea", en: "North Korea" },
  { code: 'KR', de: "Südkorea", en: "South Korea" },
  { code: 'KW', de: "Kuwait", en: "Kuwait" },
  { code: 'KZ', de: "Kasachstan", en: "Kazakhstan" },
  { code: 'LA', de: "Laos", en: "Laos" },
  { code: 'LB', de: "Libanon", en: "Lebanon" },
  { code: 'LC', de: "St. Lucia", en: "Saint Lucia" },
  { code: 'LI', de: "Liechtenstein", en: "Liechtenstein" },
  { code: 'LK', de: "Sri Lanka", en: "Sri Lanka" },
  { code: 'LR', de: "Liberia", en: "Liberia" },
  { code: 'LS', de: "Lesotho", en: "Lesotho" },
  { code: 'LT', de: "Litauen", en: "Lithuania" },
  { code: 'LU', de: "Luxemburg", en: "Luxembourg" },
  { code: 'LV', de: "Lettland", en: "Latvia" },
  { code: 'LY', de: "Libyen", en: "Libya" },
  { code: 'MA', de: "Marokko", en: "Morocco" },
  { code: 'MC', de: "Monaco", en: "Monaco" },
  { code: 'MD', de: "Moldau", en: "Moldova" },
  { code: 'ME', de: "Montenegro", en: "Montenegro" },
  { code: 'MG', de: "Madagaskar", en: "Madagascar" },
  { code: 'MH', de: "Marshallinseln", en: "Marshall Islands" },
  { code: 'MK', de: "Nordmazedonien", en: "North Macedonia" },
  { code: 'ML', de: "Mali", en: "Mali" },
  { code: 'MM', de: "Myanmar", en: "Myanmar" },
  { code: 'MN', de: "Mongolei", en: "Mongolia" },
  { code: 'MR', de: "Mauretanien", en: "Mauritania" },
  { code: 'MT', de: "Malta", en: "Malta" },
  { code: 'MU', de: "Mauritius", en: "Mauritius" },
  { code: 'MV', de: "Malediven", en: "Maldives" },
  { code: 'MW', de: "Malawi", en: "Malawi" },
  { code: 'MX', de: "Mexiko", en: "Mexico" },
  { code: 'MY', de: "Malaysia", en: "Malaysia" },
  { code: 'MZ', de: "Mosambik", en: "Mozambique" },
  { code: 'NA', de: "Namibia", en: "Namibia" },
  { code: 'NE', de: "Niger", en: "Niger" },
  { code: 'NG', de: "Nigeria", en: "Nigeria" },
  { code: 'NI', de: "Nicaragua", en: "Nicaragua" },
  { code: 'NL', de: "Niederlande", en: "Netherlands" },
  { code: 'NO', de: "Norwegen", en: "Norway" },
  { code: 'NP', de: "Nepal", en: "Nepal" },
  { code: 'NR', de: "Nauru", en: "Nauru" },
  { code: 'NZ', de: "Neuseeland", en: "New Zealand" },
  { code: 'OM', de: "Oman", en: "Oman" },
  { code: 'PA', de: "Panama", en: "Panama" },
  { code: 'PE', de: "Peru", en: "Peru" },
  { code: 'PG', de: "Papua-Neuguinea", en: "Papua New Guinea" },
  { code: 'PH', de: "Philippinen", en: "Philippines" },
  { code: 'PK', de: "Pakistan", en: "Pakistan" },
  { code: 'PL', de: "Polen", en: "Poland" },
  { code: 'PS', de: "Palästina", en: "Palestine" },
  { code: 'PT', de: "Portugal", en: "Portugal" },
  { code: 'PW', de: "Palau", en: "Palau" },
  { code: 'PY', de: "Paraguay", en: "Paraguay" },
  { code: 'QA', de: "Katar", en: "Qatar" },
  { code: 'RO', de: "Rumänien", en: "Romania" },
  { code: 'RS', de: "Serbien", en: "Serbia" },
  { code: 'RU', de: "Russland", en: "Russia" },
  { code: 'RW', de: "Ruanda", en: "Rwanda" },
  { code: 'SA', de: "Saudi-Arabien", en: "Saudi Arabia" },
  { code: 'SB', de: "Salomonen", en: "Solomon Islands" },
  { code: 'SC', de: "Seychellen", en: "Seychelles" },
  { code: 'SD', de: "Sudan", en: "Sudan" },
  { code: 'SE', de: "Schweden", en: "Sweden" },
  { code: 'SG', de: "Singapur", en: "Singapore" },
  { code: 'SI', de: "Slowenien", en: "Slovenia" },
  { code: 'SK', de: "Slowakei", en: "Slovakia" },
  { code: 'SL', de: "Sierra Leone", en: "Sierra Leone" },
  { code: 'SM', de: "San Marino", en: "San Marino" },
  { code: 'SN', de: "Senegal", en: "Senegal" },
  { code: 'SO', de: "Somalia", en: "Somalia" },
  { code: 'SR', de: "Suriname", en: "Suriname" },
  { code: 'SS', de: "Südsudan", en: "South Sudan" },
  { code: 'ST', de: "São Tomé und Príncipe", en: "São Tomé and Príncipe" },
  { code: 'SV', de: "El Salvador", en: "El Salvador" },
  { code: 'SY', de: "Syrien", en: "Syria" },
  { code: 'SZ', de: "Eswatini", en: "Eswatini" },
  { code: 'TD', de: "Tschad", en: "Chad" },
  { code: 'TG', de: "Togo", en: "Togo" },
  { code: 'TH', de: "Thailand", en: "Thailand" },
  { code: 'TJ', de: "Tadschikistan", en: "Tajikistan" },
  { code: 'TL', de: "Timor-Leste", en: "Timor-Leste" },
  { code: 'TM', de: "Turkmenistan", en: "Turkmenistan" },
  { code: 'TN', de: "Tunesien", en: "Tunisia" },
  { code: 'TO', de: "Tonga", en: "Tonga" },
  { code: 'TR', de: "Türkei", en: "Turkey" },
  { code: 'TT', de: "Trinidad und Tobago", en: "Trinidad and Tobago" },
  { code: 'TV', de: "Tuvalu", en: "Tuvalu" },
  { code: 'TW', de: "Taiwan", en: "Taiwan" },
  { code: 'TZ', de: "Tansania", en: "Tanzania" },
  { code: 'UA', de: "Ukraine", en: "Ukraine" },
  { code: 'UG', de: "Uganda", en: "Uganda" },
  { code: 'US', de: "Vereinigte Staaten", en: "United States" },
  { code: 'UY', de: "Uruguay", en: "Uruguay" },
  { code: 'UZ', de: "Usbekistan", en: "Uzbekistan" },
  { code: 'VA', de: "Vatikanstadt", en: "Vatican City" },
  { code: 'VC', de: "St. Vincent und die Grenadinen", en: "Saint Vincent and the Grenadines" },
  { code: 'VE', de: "Venezuela", en: "Venezuela" },
  { code: 'VN', de: "Vietnam", en: "Vietnam" },
  { code: 'VU', de: "Vanuatu", en: "Vanuatu" },
  { code: 'WS', de: "Samoa", en: "Samoa" },
  { code: 'XK', de: "Kosovo", en: "Kosovo" },
  { code: 'YE', de: "Jemen", en: "Yemen" },
  { code: 'ZA', de: "Südafrika", en: "South Africa" },
  { code: 'ZM', de: "Sambia", en: "Zambia" },
  { code: 'ZW', de: "Simbabwe", en: "Zimbabwe" },
]
