// src/modules/admin/components/__tests__/membersColumns.fixture.ts
//
// The exact column list of `members` on PROD, in ordinal order, read from
// information_schema on 2026-08-06 (100 columns), + migration 299's four fee
// override columns (104):
//
//   ssh hetzner "sudo docker exec kscw-postgres psql -U supabase_admin -d postgres \
//     -At -c \"select column_name from information_schema.columns \
//     where table_name='members' order by ordinal_position\""
//
// memberFieldSchema.test.ts asserts MEMBER_FIELDS covers exactly this list, so
// a migration that adds a column fails the unit suite until the column is given
// a group, a label and (if it is machine-written) a provenance string. That is
// the whole point: a column nobody classified is a column the Data Explorer
// would render as an anonymous text box.
//
// Re-run the query above and update this file in the SAME commit as the
// migration that changes the table.

export const MEMBERS_COLUMNS: string[] = [
  'id',
  'email',
  'first_name',
  'last_name',
  'phone',
  'license_nr',
  'number',
  'position',
  'photo',
  'role',
  'kscw_membership_active',
  'birthdate',
  'coach_approved_team',
  'language',
  'hide_phone',
  'birthdate_visibility',
  'website_visible',
  'wiedisync_active',
  'shell',
  'shell_expires',
  'shell_reminder_sent',
  'requested_team',
  'user',
  'date_created',
  'date_updated',
  'is_spielplaner',
  'adresse',
  'plz',
  'ort',
  'nationalitaet',
  'anrede',
  'ahv_nummer',
  'beitragskategorie',
  'licence_category',
  'licence_activated',
  'licence_validated',
  'vm_email',
  'sex',
  'communications_team_chat_enabled',
  'communications_dm_enabled',
  'communications_banned',
  'push_preview_content',
  'last_online_at',
  'consent_prompted_at',
  'consent_decision',
  'last_export_at',
  'hide_email',
  'scorer_vb',
  'referee_vb',
  'otr1_bb',
  'otr2_bb',
  'otn_bb',
  'referee_bb',
  'auto_confirm_trainings',
  'auto_confirm_games',
  'auto_confirm_events',
  'website_name_private',
  'iban',
  'ical_token',
  'billing_different',
  'billing_name',
  'billing_email',
  'billing_address',
  'billing_plz',
  'billing_ort',
  'billing_phone',
  'sektion',
  'billing_iban',
  'iban_confirmed',
  'never_dun',
  'email_notify_registrations',
  'email_notify_join_requests',
  'email_notify_form_submissions',
  'email_notify_announcements',
  'email_notify_events',
  'clubdesk_id',
  'clubdesk_push_pending',
  'clubdesk_push_changes',
  'clubdesk_pushed_at',
  'uuid',
  'clubdesk_sync_exclude',
  'js_id',
  'e2ee_public_key',
  'e2ee_private_key',
  'e2ee_kdf_salt',
  'e2ee_key_created',
  'nickname',
  'nationalitaet_codes',
  'federation_of_origin',
  'otn1_bb',
  'otn2_bb',
  'transfer_status',
  'transfer_done_at',
  'transfer_done_by_name',
  'transfer_note',
  'in_vis',
  'in_vis_checked_at',
  'vis_player_no',
  'profile_verified_at',
  'trainer_licences',
  // Migration 299 — per-member Beitrag overrides.
  'fee_base_override',
  'fee_surcharge_override',
  'fee_discount',
  'fee_discount_reason',
]
